//
//  LatestTypeEffectivenessTable.swift
//  swift-pokemon-types
//  
//  Created by elmetal on 2026/04/26
//  
//

public struct LatestTypeEffectivenessTable: TypeEffectivenessTable {
    public init() {}

    public func effectiveness(of attackingType: PokemonType,
                              against defendingType: PokemonType) -> TypeEffectiveness {
        switch (attackingType, defendingType) {
        case (.normal, .ghost),
             (.fighting, .ghost),
             (.poison, .steel),
             (.ground, .flying),
             (.ghost, .normal),
             (.electric, .ground),
             (.psychic, .dark),
             (.dragon, .fairy):
            .ineffective

        case (.normal, .rock),
             (.normal, .steel),
             (.fighting, .flying),
             (.fighting, .poison),
             (.fighting, .bug),
             (.fighting, .psychic),
             (.fighting, .fairy),
             (.flying, .rock),
             (.flying, .steel),
             (.flying, .electric),
             (.poison, .poison),
             (.poison, .ground),
             (.poison, .rock),
             (.poison, .ghost),
             (.bug, .fighting),
             (.bug, .flying),
             (.bug, .poison),
             (.bug, .ghost),
             (.bug, .steel),
             (.bug, .fire),
             (.bug, .fairy),
             (.steel, .steel),
             (.steel, .fire),
             (.steel, .water),
             (.steel, .electric),
             (.psychic, .steel),
             (.psychic, .psychic),
             (.ice, .steel),
             (.ice, .fire),
             (.ice, .water),
             (.ice, .ice),
             (.dragon, .steel),
             (.dark, .fighting),
             (.dark, .dark),
             (.dark, .fairy),
             (.fairy, .poison),
             (.fairy, .steel),
             (.fairy, .fire),
             (.fire, .rock),
             (.fire, .fire),
             (.fire, .water),
             (.fire, .dragon),
             (.water, .water),
             (.water, .grass),
             (.water, .dragon),
             (.grass, .flying),
             (.grass, .poison),
             (.grass, .bug),
             (.grass, .steel),
             (.grass, .fire),
             (.grass, .grass),
             (.grass, .dragon),
             (.electric, .grass),
             (.electric, .electric),
             (.electric, .dragon),
             (.ground, .bug),
             (.ground, .grass),
             (.rock, .fighting),
             (.rock, .ground),
             (.rock, .steel),
             (.ghost, .dark):
            .notVeryEffective

        case (.fighting, .normal),
             (.fighting, .steel),
             (.fighting, .ice),
             (.fighting, .dark),
             (.fighting, .rock),
             (.flying, .fighting),
             (.flying, .bug),
             (.flying, .grass),
             (.poison, .fairy),
             (.poison, .grass),
             (.bug, .psychic),
             (.bug, .dark),
             (.bug, .grass),
             (.steel, .fairy),
             (.steel, .ice),
             (.steel, .rock),
             (.psychic, .fighting),
             (.psychic, .poison),
             (.ice, .flying),
             (.ice, .dragon),
             (.ice, .grass),
             (.ice, .ground),
             (.dragon, .dragon),
             (.dark, .ghost),
             (.dark, .psychic),
             (.fairy, .fighting),
             (.fairy, .dragon),
             (.fairy, .dark),
             (.fire, .bug),
             (.fire, .steel),
             (.fire, .ice),
             (.fire, .grass),
             (.water, .fire),
             (.water, .ground),
             (.water, .rock),
             (.grass, .water),
             (.grass, .ground),
             (.grass, .rock),
             (.electric, .flying),
             (.electric, .water),
             (.ground, .poison),
             (.ground, .steel),
             (.ground, .fire),
             (.ground, .electric),
             (.ground, .rock),
             (.rock, .flying),
             (.rock, .bug),
             (.rock, .fire),
             (.rock, .ice),
             (.ghost, .ghost),
             (.ghost, .psychic):
            .superEffective

        default:
            .neutral
        }
    }
}
